js/modules/auth/html/login.tmpl.html
Image not showing up if homer installed in sub-folder
=> small typo on login page

js/widgets/adminnode/adminnode.js
Fixed console log messages for node operations.
Fixed Issue#8: at line 266 $scope.node renamed into $scope.noderec
Fixed tab closure function name in call.
=> Issue#8 fix

js/widgets/adminalias/adminalias.js
Fixed remove*Tab method name for $scope object.
Fixed object name in debug messages.
Fixed field name in deletion method. ($scope.alias renamed into $scope.arec)
=> UI::Alias client side fixes

js/modules/pages/controllers/dialogCtrl.js
There was now properties offsetX and offsetY on MFF under Ubuntu Desktop 14
Need to be tested on windows browsers.
=> FIXED: Unable to open messages from the call flow dialog

js/widgets/clock/timezones.js, templates/left-panel.html
Dynamic "hidden" class was added.
=> FIX: part of left-side menu still were visible while menu was hidden

js/modules/pages/controllers/resultCtrl.js
Search result grid: Added tooltip support for source and destination IP addresses: if alias is defined it will be displayed and tooltip will display IP, IP will be diaplyed everywhere otherwise.
Code formatted aswell.
=> Kvishnivetsky patch aliases support

js/widgets/quicksearch/quicksearch.html, js/widgets/quicksearch/quicksearch.js
Refers to homer-api pull request #41 by mslehto
=> Added To, From and RURI domain parts to quicksearch widget

js/modules/pages/controllers/resultCtrl.js
=> Add to_user to result table

js/modules/pages/controllers/resultCtrl.js
We have added support for the "orand" Parameter to ad-hoc GET search results in the UI resultController
=> add orand parameter to GET search result request

share/controller.js, share/index.html
First release of RTCP UI dashbourd
=> RTCP UI dashbourd implementation

css/voicenter-style.css
=> Adding the css file

configure.ac
=> Updates for Oracle Linux installation

js/modules/pages/controllers/resultCtrl.js
Those search functions were integrated in commits
https://github.com/sipcapture/homer-ui/commit/576797d9b5cbc6bca32e2638e0b2e3c7983342c1#diff-0b53e68572292f45122bc64e1c057487
https://github.com/sipcapture/homer-ui/commit/7d754e378ae40e0df74a62ca66259330dbe8f48a#diff-0b53e68572292f45122bc64e1c057487
but mysteriously got lost again in
https://github.com/sipcapture/homer-ui/commit/7beb3674492e2ec590626480c3ecb3adf179fac2#diff-0b53e68572292f45122bc64e1c057487
This commit reintroduces those two options again.
=> Add two search options and/or and pid_user again.

css/report-style.css, templates/dialogs/transaction.html
For more information in detail please take a look here:
https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/xrtpv32.pdf
=> Extend X-RTP-Stat header information

js/controller.js
Adds NZST (GMT+12) and NZDT (GMT+13)
Correction to AEST
=> Fix for https://github.com/sipcapture/homer/issues/200

js/modules/pages/controllers/dialogCtrl.js
For SIP there are invididual lines already, for ISUP there is only
the raw JSON string. Start to parse the JSON and display the data
in a table like structure. Put some common fields first and then
the rest. Assume that no HTML tags come from the homer-api and that
no json object has a nesting higher two.
Keep the name as sipMessage as the view code seems to use the name.
=> message display: Format an ISUP message differently

js/modules/core/services/profile.js
This will be a temporary fix for the following issue https://github.com/sipcapture/homer/issues/325, as we need to further investigate on API returning invalid json data.
=> Fix search is not working due to invalid JSON data

package-lock.json, src/VERSION.ts, src/app/components/search-grid-call/detail-dialog/detail-dialog.component.css, src/app/components/search-grid-call/detail-dialog/tab-hepsub/tab-hepsub.component.html, src/app/components/search-grid-call/detail-dialog/tab-hepsub/tab-hepsub.component.ts, src/app/components/search-grid-call/detail-dialog/tab-loki/tab-loki.component.html, src/app/components/search-grid-call/detail-dialog/tab-messages/tab-messages.component.html, src/app/components/search-grid-call/message-content/message-content.component.css, src/app/components/search-grid-call/message-content/message-content.component.html, src/app/components/search-grid-call/message-content/message-content.component.ts, src/app/helpers/functions.ts, src/styles.scss
fixed colors INVITE and LOGS
fix: sipcapture/homer-app#256 remake TAB styles
fix: change design 'Refresh search' into LOGS/TAB-Loki
VERSION 7.7.018
=> VERSION 7.7.018

src/app/components/search-grid-call/detail-dialog/tab-flow/tab-flow.component.ts
Should now handle both IPv4 and IPv6
There are probably a thousand and one ways to achieve this, and this is but one...
=> Attempt to fix IP:port split for GUI display. 

src/app/components/search-grid-call/detail-dialog/tab-flow/tab-flow.component.ts
if the one we got (eg from SIP headers) already contains it.
=> Avoid wrapping IPv6 in [] 

src/app/components/preference/preference.component.ts, src/app/components/widgets/protosearch-widget/protosearch-widget.component.ts, src/app/components/widgets/smart-input-widget/setting-smart-input-widget.component.html, src/app/components/widgets/smart-input-widget/setting-smart-input-widget.component.scss, src/app/components/widgets/smart-input-widget/setting-smart-input-widget.component.ts, src/app/components/widgets/smart-input-widget/smart-input-widget.component.ts
- Smart input protocol settings
- Results Multi-select "when page and container target selected" error fix
- "User Settings" extra column removal
=> Alexey dev

src/app/components/search-grid-call/detail-dialog/detail-dialog.component.ts, src/app/components/widgets/index.ts
=> Transaction dialog default filters

.gitignore, src/app/components/search-grid-call/detail-dialog/tab-flow/tab-flow.component.html, src/app/components/search-grid-call/detail-dialog/tab-flow/tab-flow.component.scss
=> Call flow styles

angular.json, package-lock.json, package.json, src/app/app.module.ts, src/app/components/menu/menu.component.ts, src/app/components/preference/preference.component.ts, src/app/components/search-grid-call/detail-dialog/detail-dialog.component.html, src/app/components/search-grid-call/detail-dialog/detail-dialog.component.ts, src/app/components/search-grid-call/detail-dialog/tab-flow/tab-flow.component.html, src/app/components/search-grid-call/detail-dialog/tab-flow/tab-flow.component.scss, src/app/components/search-grid-call/detail-dialog/tab-flow/tab-flow.component.ts, src/app/components/search-grid-call/detail-dialog/tab-messages/tab-messages.component.html, src/app/components/search-grid-call/detail-dialog/tab-messages/tab-messages.component.scss, src/app/components/search-grid-call/detail-dialog/tab-messages/tab-messages.component.ts, src/app/components/search-grid-call/detail-dialog/tab-qos/tab-qos.component.html, src/app/components/search-grid-call/detail-dialog/tab-qos/tab-qos.component.ts, src/app/components/search-grid-call/search-grid-call.component.html, src/app/components/search-grid-call/search-grid-call.component.ts, src/app/qos.worker.ts, src/app/services/worker.service.ts, src/environments/environment.dev.ts, src/tsconfig.app.json, tsconfig.worker.json
- fix: CSS on Message-tab and on FLOW tab
- added ng-table-virtual-scroll for message tab on transaction window
- added Web-Worker for QoS as QoS-processor
- fix: preference(setting page) performance optimisation
=> performance optimisation & Web-Worker

src/app/components/search-grid-call/detail-dialog/tab-flow/tab-flow.component.html, src/app/components/search-grid-call/detail-dialog/tab-flow/tab-flow.component.scss, src/app/components/search-grid-call/detail-dialog/tab-flow/tab-flow.component.ts
fix: Transaction / FLOW scroller issue
=> fix: Transaction / FLOW scroller issue

src/app/components/search-grid-call/message-content/message-content.component.html, src/app/components/search-grid-call/message-content/message-content.component.ts
- fix: Message Details - LOG format
=> fix: Message Details - LOG format

src/app/components/search-grid-call/detail-dialog/tab-flow/tab-flow.component.ts
=> fix: https://github.com/sipcapture/homer/issues/477 SDP packet indicator in flow view

src/VERSION.ts, src/app/components/search-grid-call/detail-dialog/tab-flow/tab-flow.component.ts, src/app/components/search-grid-call/detail-dialog/tab-messages/tab-messages.component.html, src/app/components/search-grid-call/detail-dialog/tab-messages/tab-messages.component.ts, src/environments/environment.prod-noenv.ts, src/environments/environment.prod.ts
fix: SDP packet indicator in on tab MESSAGES
=> fix: SDP packet indicator in on tab MESSAGES

src/app/components/search-grid-call/detail-dialog/detail-dialog.component.ts, src/app/components/search-grid-call/detail-dialog/tab-callinfo/tab-callinfo.component.ts, src/app/components/search-grid-call/search-grid-call.component.ts, src/app/services/search.service.ts, src/app/services/session-storage.service.ts
fixes [#479](https://github.com/sipcapture/homer/issues/479) Homer repo
=> fix #479 search broken on clear localstorage

src/VERSION.ts, src/app/components/search-grid-call/detail-dialog/detail-dialog.component.ts, src/app/components/search-grid-call/detail-dialog/tab-callinfo/tab-callinfo.component.ts, src/app/components/search-grid-call/detail-dialog/tab-flow/tab-flow.component.ts, src/app/components/search-grid-call/detail-dialog/tab-messages/tab-messages.component.html, src/app/components/search-grid-call/detail-dialog/tab-messages/tab-messages.component.ts, src/app/components/search-grid-call/search-grid-call.component.ts, src/app/services/search.service.ts, src/app/services/session-storage.service.ts, src/environments/environment.prod-noenv.ts, src/environments/environment.prod.ts
=> UPDATE VERSION up to 7.9.16

src/app/components/search-grid-call/detail-dialog/tab-flow/tab-flow.component.ts, src/app/components/search-grid-call/detail-dialog/tab-messages/tab-messages.component.ts, src/app/components/search-grid-call/message-content/message-content.component.ts
Fix: SDP indicator on MESSAGES & FLOW
=> Fix: SDP indicator on MESSAGES & FLOW

src/app/components/menu/menu.component.html, src/app/components/menu/menu.component.scss, src/app/components/menu/menu.component.ts, src/app/components/preference/dialogs/dialog-users/dialog-users.component.ts, src/app/components/preference/pages/page-profile/page-profile.component.html, src/app/components/preference/pages/page-profile/page-profile.component.scss, src/app/components/preference/pages/page-profile/page-profile.component.ts, src/app/helpers/functions.ts, src/app/models/user.model.ts
+ add dynamic avatar coloring by uuid
+ improve user profile page styles and information display
=> styles fix for user profile

src/app/components/search-grid-call/detail-dialog/tab-flow/tab-flow.component.ts
fix: #518 sip flow ui - inability to scroll down after scrolling right, tested & fixed mistakes
=> fix: #518 sip flow ui - inability to scroll down after scrolling right, tested & fixed mistakes

src/app/components/search-grid-call/detail-dialog/tab-export/tab-export.component.html, src/app/components/search-grid-call/detail-dialog/tab-hepsub/tab-hepsub.component.html, src/app/components/search-grid-call/detail-dialog/tab-hepsub/tab-hepsub.component.ts, src/app/components/search-grid-call/detail-dialog/tab-hepsub/tab-hepsub.module.ts, src/app/helpers/functions.ts, src/app/services/agentsub.service.ts, src/app/services/call/full-transaction.service.ts, src/app/services/preferences/agentsub.service.ts
This provides support for seeking and retrieving files from HEPSUB agents, including support for multiple agent subscriptions.
=> :sparkles: Allow file download from HEPSUB subscribers

src/app/components/search-grid-call/detail-dialog/tab-flow/tab-flow.component.ts, src/app/components/search-grid-call/message-content/message-content.component.html, src/app/components/search-grid-call/message-content/message-content.component.ts
=> fix: HEP-LOG parser on FLOW dialog-details

src/app/components/controls/transaction-filter/transaction-filter.component.ts
needs add on Preference/Advenced -> 
category: transaction
param: filter
data:
```json
{
"SIP": true,
"RTP": true,
"RTCP": true,
"LOG": false,
"HEP-LOG": false 
}
```
=> 632 setting default display filter behavior

src/VERSION.ts, src/app/components/search-grid-call/search-grid-call.component.ts
- fix https://github.com/sipcapture/homer-app/issues/610
=> fix: Extra space chars in web-interface added #610

src/app/components/search-grid-call/detail-dialog/detail-dialog.component.ts, src/app/services/call/full-transaction.service.ts
=> fix: Homer UI does not display Jitter/Loss/MOS stats homer-app#612
